#!/bin/sh

set -e # using the options command to abort script at first error
echo "Running the 'pre-commit' script"
echo "\tRunning back-end unit-tests"
cd ./back-end
npm test
echo "\tRunning front-end unit-tests"
cd ../front-end
npm test
echo "Success! All unit-tests passed!"

# check if pushing to master
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $current_branch = "master" ] then
	echo
	echo -e "Pushing to master...\n\tPerforming additional quality checks"
	echo -e "\tRunning UI acceptance tests"
	npm run acceptance

	exit 1
fi

exit 0