#!/bin/sh

set -e # using the options command to abort script at first error
echo "Running the 'pre-commit' script"
echo "\tRunning Back-end Linter..."
cd ./back-end
npm run linter
echo "\tRunning Front-end Linter..."
cd ../front-end
npm run linter
echo "Success! No linter errors detected"