#!/bin/sh

set -e # using the options command to abort script at first error
echo "Running the 'pre-commit' script"
echo "\tRunning back-end unit-tests"
cd ./back-end
npm test
echo "\tRunning front-end unit-tests"
cd ../front-end
npm test
echo "Success! All unit-tests passed!"

echo -e "\tRunning UI acceptance tests"
npm run acceptance