image: node:latest

stages:
  - code-tests
  - unit-tests
  - staging
  - deployment

cache:
  paths:
  - node_modules/

# lint-backEnd:
#   stage: code-tests
#   script:
#     - cd back-end/
#     - npm install
#     - npm run linter

# lint-frontEnd:
#   stage: code-tests
#   script:
#     - cd front-end/
#     - npm install
#     - npm run linter

# test-backEnd:
#   stage: unit-tests
#   script:
#     - cd back-end/
#     - npm install
#     - npm test

# test-frontEnd:
#   stage: unit-tests
#   script:
#     - cd front-end/
#     - npm install
#     - npm test

# dc-backEnd:
#   stage: staging
#   script:
#     - cd back-end/
#     - npm install
#     - npm run dc

deploy-frontend:
  stage: deployment
  before_script:
    - git remote add heroku-api https://git.heroku.com/mitch137-test.git
  script:
    - ./commands/deploy_frontend.sh

deploy-backend:
  stage: deployment
  before_script: 
    - git remote add heroku-api https://git.heroku.com/mitch137-test-api.git
  script:
    - ./commands/deploy_backend.sh

# ui-test-frontEnd:
#   image: alekzonder/puppeteer:1.5.0-0
#   stage: acceptance-tests
#   script:
#       - cd back-end/
#       - npm install
#       - cd ../front-end/
#       - npm install
#       - npm run acceptance
#   artifacts:
#     paths:
#      - test/screenshots/*/*
#     expire_in: 3 days
