image: node:latest

stages:
  - code-tests
  - unit-tests
  - acceptance-tests

cache:
  paths:
  - node_modules/

lint-backEnd:
  stage: code-tests
  script:
    - cd back-end/
    - npm install
    - npm run linter

lint-frontEnd:
  stage: code-tests
  script:
    - cd front-end/
    - npm install
    - npm run linter

test-backEnd:
  stage: unit-tests
  script:
    - cd back-end/
    - npm install
    - npm test

test-frontEnd:
  stage: unit-tests
  script:
    - cd front-end/
    - npm install
    - npm test

# ui-test-frontEnd:
#     stage: acceptance-tests
#     script:
#         - cd back-end/
#         - npm install
#         - cd ../front-end/
#         - npm install
#         - npm run acceptance
