image: node:latest

stages:
  - test

lint:
  stage: test
  script:
    - cd back-end/
    - npm install
    - npm run linter

test:
  stage: test
  script:
    - cd back-end/
    - npm install
    - npm test
