image: node:latest

stages:
  - code-tests
  - unit-tests
  - staging
  - deployment-back
  - deployment-front

cache:
  paths:
  - node_modules/

# lint-backEnd:
#   stage: code-tests
#   script:
#     - cd back-end/
#     - npm install
#     - npm run linter

# lint-frontEnd:
#   stage: code-tests
#   script:
#     - cd front-end/
#     - npm install
#     - npm run linter

# test-backEnd:
#   stage: unit-tests
#   script:
#     - cd back-end/
#     - npm install
#     - npm test

# test-frontEnd:
#   stage: unit-tests
#   script:
#     - cd front-end/
#     - npm install
#     - npm test

# dc-backEnd:
#   stage: staging
#   script:
#     - cd back-end/
#     - npm install
#     - npm run dc
  
deploy-backend:
  stage: deployment-back
  before_script:
    - cd back-end/
  script:
    - apt-get update -yq
    - apt-get install ruby-dev rubygems -y
    - gem install dpl
    - dpl --provider=heroku --app=mitch137-test-api --api-key=81eaf2cb-7d8a-42dc-89d8-b3eb55887702

deploy-frontend:
  stage: deployment-front
  before_script:
    - cd front-end/
  script:
    - apt-get update -yq
    - apt-get install ruby-dev rubygems -y
    - gem install dpl
    - dpl --provider=heroku --app=mitch137-test --api-key=81eaf2cb-7d8a-42dc-89d8-b3eb55887702

# ui-test-frontEnd:
#   image: alekzonder/puppeteer:1.5.0-0
#   stage: acceptance-tests
#   script:
#       - cd back-end/
#       - npm install
#       - cd ../front-end/
#       - npm install
#       - npm run acceptance
#   artifacts:
#     paths:
#      - test/screenshots/*/*
#     expire_in: 3 days
